<h2>Cyberspace</h2>
<p>A combination of events such as coordinated cyber attacks, or a cyber incident occurring during a disaster of another kind, should be a serious concern for policy makers. According to the Organisation for Economic Co-operation and Development (OECD) (January 2011), Governments and policy-makers should plan to withstand and recover from cyber events, both accidental and deliberate, although (it reported) very few single cyber-related events have the capacity to cause <a href="#" class="ellipsis-control">global catastrophe 1 &hellip;</a></p>

<section class="ellipsis">
    <p>But, there are significant and growing risks of <q>localised misery and loss as a result of compromised computer and telecommunications services</q>. Reliable internet and other computer facilities are essential, for example, for recovery from large-scale disasters.</p>
    <p>It is not useful to use the term cyber war to describe espionage, hacktivist blockading, spear-phishing or defacing of websites, as recently seen in connection with WikiLeaks. The Guardian said on 17 January 2011 that the report came at a time of "heightened awareness of online attacks", following hacking protests against companies caught up in the WikiLeaks controversy.</p>
    <p>The OECD study found that it was highly unlikely there would ever be "a pure cyber war fought solely in cyberspace" with equivalent effects to recent wars in Afghanistan, the Balkans or the Middle East.</p>
    <p>The study took the view that very few single <cite>cyber events</cite> could cause a global shock. Possible examples included a successful attack on one of the technical protocols on which the Internet depends, or a large solar flare wiping out key communications components such as satellites.</p>
    <p>However, as cyber weapons can be used with a degree of anonymity, threats of reprisals (and international treaties) may be baseless. Systems are as secure as the staff who run them.</p>
    <p>Note that China says its plan to build a "cyber blue team" is a training mechanism to defend the national internet, not a "hacker's army".</p>
    <p>The IMF said in June 2011 that it had been targeted by a sophisticated cyber attack that had breached its systems with the hack intending to install software that would create a "digital insider presence".</p>
    <p>The London Conference on Cyberspace, 1-2 November 2011 reviewed key issues - from potential cyber attacks on intelligence information and infrastructure to intellectual property rights and copyright infringement. The evolving cyber security vulnerabilities of governments, businesses, and individuals require continuous dialogue on how to create a safe online environment while utilizing the internet’s full potential for stimulating economic growth and information exchange.</p>
    <p>The OECD report concluded that cyber weaponry would be <cite>increasingly deployed and with increasing effect by ideological activists of all persuasions and interests</cite>.</p>
    <p>The United States is preparing for cyber conflict, and has launched its own military cyber command. The UK in October 2010 rated cyber attacks as one of the top external threats, promising to spend an extra £650 million ($1 billion US) on the issue.</p>
    <p>Two recently unverified cyber attacks with military overtones related to Iran (slowing down its uranium processing), and Syria (disabling its airspace to allow Israeli aircraft to damage nuclear installations).</p>
</section>
