<h2>Questions</h2>
<p>Work on implementing EU Enlargement and European Neighbourhood Policy (ENP) raises interesting questions about Europe's future. Many of the issues (but certainly not all) relate to the changes that are currently taking place in the Ukraine, as well as the Middle East and North Africa (MENA) region, and particularly Syria.  The answers to the questions are not obvious.</p>
<ul>
<li>Does the EU need to define its ultimate borders? Do tomorrow's final enlargement lines have to be drawn today? Will the EU inevitably evolve into the Wider European Union, and include the MENA countries?</li>
<li>How much longer can al-Assad be given leeway to crack down on popular protests? Will there be a post-Assad Syria? If so, will it splinter between the ruling Alawites, the elite and urban Christians, the majority Sunnis, the Kurds, Druze and others? How can civil society be developed quickly to engineer a peaceful transition, so that Syria does not become another Lebanon? How can outside players use innovative, soft power strategies to help develop Syrian democracy? Who is winning the propaganda war? How many refugees have crossed the border with Turkey, and how long can they stay there? </li>
<li>What are the Arab League's Red Lines? Are they listening to the Syrian Revolution Coordination Union's slogan - your silence is killing us?</li>
</ul>
<p><a href="#" class="ellipsis-control"><span class="open">Read More&hellip;</span><span class="close">Show Less&hellip;</span></a></p>
<ul class="ellipsis">
<li>Tunisia's Jasmine Revolution, Egypt's Nile Revolution and Libya's Martyrs' Revolution; rage in Jordan, Iran, Morocco, Algeria and Iraq; uprisings in Bahrain and Saudi Arabia; Yemen, post-Saleh; and serious government repression in Syria. Which stress tests are being applied, and by whom? In which way will evolving MENA events be a permanent game-changer? How will the regional power matrix balance alter?</li>
<li>Two positives of the Arab Spring are that it has not (yet) been anti-Western or terrorist-driven. Is it delivering an Islamic Enlightenment, particularly for Muslim women? Today's MENA protesters know what they are against: do they agree on what they want - evolution through revolution; home-grown rather than imposed democracy; freedom to choose their own destiny, without chaos; and not being talked down to? How large will be the democracy movement in the MENA region? Will individual country dynamics stop a domino effect?</li>
<li>Following European military intervention in Libya, has this hastened evolution of the EU's military capability? If so, how large will it get? When will the European Policeman choose to intervene militarily: on principle, or only when it knows it cannot lose? What size and composition of EU (as well as NATO an arab) military machine would be required to take on Syria?</li>
<li>Could political instability and domestic upheavals in the MENA region spill over into the EU? If so, what threats would this pose? To what extent does the current ENP reflect the EU's security needs?</li>
<li>Between now and 2050, Europe's workforce will decrease by 70 million. Maintaining the economy will require migration and open EU borders. How can the populist movements in Europe that would shun "outsiders" be faced down? The ENP seeks to strike a balanced migration management strategy whereby illegal immigrants are kept out but highly skilled workers from neighbouring countries are welcomed: can this work in practice? Are some EU member states correct in expressing alarm at increased migration from the Maghreb? Do the numbers stack up? Is migration going to be the EU's biggest problem ever, (or the solution to its problems)?</li>  
<li>Will the EU's Schengen passport-free area run aground? Are the financial (and linked political) crises in the GIPSI countries simply a warning, or an inevitable fate for all current EU members of the Eurozone? Is the whole European project starting to unravel? Can it be re-floated?</li>
<li>As the EU now accounts for 75% of foreign investment in Turkey and roughly half its exports and inward tourism, and as Europe's energy security depends on cooperation with Turkey on the transit of oil and natural gas from Central Asia and the Middle East, how can the EU continue to be blind to Turkey's full membership? How can Europe cooperate with it and other neighbourhood hydrocarbon suppliers, including Russia, to guarantee its future energy needs at an affordable price? </li>
<li>Do the MENA countries' political and economic spaces represent an untapped opportunity for the EU? Are new inner clubs/groups within the EU driving towards deeper integration with the MENA region? Does strengthening links between all neighbourhood countries move them towards a larger free market zone? If so, does this strengthen, or make more vulnerable, the network of economies? </li>
<li>Would European neighbourhood states be more comfortable with a "two speed" Europe with which they could form looser associations without having to take on the obligations and responsibilities of the acquis communautaire? Would the current 28 member states agree to a two-speed solution as an acceptable price for having a stable European neighbourhood? What views should European neighbourhood countries take of EU internal integration? Should they be suspicious of the emergence of a European super state?</li>
<li>Should the EU be so cautious about holding out the prospect of eventual membership to neighbourhood countries such as the Ukraine and Moldova? What can the EU do about Lukashenko's regime in Belarus?</li>  
<li>What is the EU's timetable for opening up its markets to African products whilst phasing down aid flows to that continent?</li>
<li>What evidence is there that the new European diplomatic service is making an impact?</li>
<li>Would a Middle East peace settlement introduce a new regional and economic dynamic? Will the May 2011 reconciliation pact signed in Cairo between Fatah and Hamas facilitate such an agreement? Why wasn't a new Palestinian State recognised by the UN in September 2011? What is the EU's role in tackling the Middle East peace process, and how can it be enhanced? Is the Arab world's continuing upheaval stopping the Palestinian-Israeli conflict from being resolved? Can the Israelis reach a peace accord, based on the pre-1967 borders, at a time when all the pieces of the current Arab puzzle are not yet in place? What will be the political impact of Egypt opening the Rafah border to ease the four-year blockade on Palestinians living in the Gaza Strip?</li>  
<li>What are the red lines of the Arab League (22 countries) and Gulf Cooperation Council (Saudi Arabia, plus Bahrain, Kuwait, Oman, Qatar and the UAE, as well as possible candidates, Jordan and Morocco)? Why can't they stop the government crack-down in Syria?</li>
<li>How does Washington reconcile its willingness to back with force the opposition in Libya, but not in Yemen (Al-Qaeda, ungoverned spaces), Bahrain (US 5th Fleet) and Saudi Arabia (oil supplies), as well as the regional nexus that is Syria (anti-Israel, pro-Iran, strategic player in Middle East politics, Russian influence - basically "radioactive")? </li>
<li>What is happening to Al-Qaeda, particularly in Yemen? Who will move it forward, and from which organisational base?</li> 
<li>Which economic/social model should European neighbourhood countries follow: Anglo-Saxon or Franco-German? Is either appropriate and relevant in the emerging democracies of the MENA region? How does Turkey define its model? Is it a "one size fits all" that MENA countries could follow? How can it be when, as Ataturk's secular state, it is not Muslim, let alone Arab? Can its (blocked) progress towards EU accession send a positive signal to MENA people who want democracy and prosperity? Can the EU "reset" negotiations over Turkish membership, so that, with Turkey IN, the EU will be able to play a more positive and dynamic role in the current MENA democratisation process, particularly in Syria?</li>
<li>Does NATO have the bandwidth to cope with what is happening in Syria and the other MENA countries, and keep its eye on the Iranian ball?</li>
<li>Can the EU realistically support fledgling MENA democracies when it cannot consolidate one within its own borders: how can EU-Turkey cooperation in Bosnia-Herzegovina achieve a durable solution? Will unrest in the MENA zone have an impact on potential candidate countries in the Balkans, as well as in the Caucasus countries?</li>
<li>For how long can repressive governments in the MENA region stop the current struggle for democracy and freedom? Can they control the globally available communications' technology that is helping to drive forward and mobilise dissent? Will China, Iran and Azerbaijan be able to pre-empt similar uprisings?</li>
<li>How likely is it that the EU will forge common policies on tax and "the social model", completion of the single market, energy, defence, immigration and organised crime? And, as the rationale for Europe today is about future power, not post-war peace, how can the EU use its collective weight to be an active global player, rather than a museum, in a world where China is increasingly dominant? Does the EU need an elected President to facilitate all of this, (as well as ensure that Turkey becomes a full member)?</li>
</ul>