<h2>People</h2>

<p>Whilst WIDER EUROPE is for everybody, a major target audience is today's <strong>young people</strong> who live within the European Neighbourhood - its future citizens, voters, parents, employers, employees, media, politicians and members of civil society. Their capacity to social network, (for example, through <a href="http://www.movements.org">movements.org</a> and the <a href="http://www.oslofreedomforum.com/">Oslo Freedom Forum</a>), allows them to (a) stage-manage and coordinate current political protests (via Facebook, Twitter and Youtube), (b) use multiple information sources to act as citizen journalists, (c) increase social interaction and accountability, as well as (d) develop Wider Europe's emerging civil society. There is now "power diffusion" by non-state actors who increasingly do what the state used to do. <a href="#" class="ellipsis-control"><span class="open">Read more&hellip;</span><span class="close">Show less&hellip;</span></a></p>

<section class="ellipsis">
<p>A necessary condition for Wider European society to work properly is that its people have easy access to available information. But it is sometimes difficult for non-specialists to know where to look first. WIDER EUROPE provides links to useful websites relevant to the current debate about (a) <a href="http://ec.europa.eu/enlargement/index_en.htm">further EU Enlargement</a>, (b) <a href="http://ec.europa.eu/world/enp/welcome_en.htm">European Neighbourhood Policy</a> (including the May 2011 <a href="http://ec.europa.eu/world/enp/pdf/com_11_303_en.pdf">neighbourhood policy update</a>), and (c) Britain's role in tomorrow's EU.</p> 
<p>The websites refer to changing economic, social, environmental and geo-political ideas that are being developed in the public, private and third sectors, as well as by the fourth estate. If you are interested in these areas, whether as an individual, journalist, photographer, analyst, video/photo-reporter, activist or musician, or as a result of working for an environmental pressure group, trade union, faith-based organization, national democracy movement, CSO/NGO, think tank/lobby group, university, multilateral/bilateral donor, media-based organisation, the private sector, government department or whatever, then WIDER EUROPE is for you.</p> 

<p>A radio station for all people, WIDER EUROPE plays music 52/24/7. It accesses a live news stream in English from <a href="http://www.aljazeera.com/watch_now/">Al Jazeera</a> (click on its Play button). For those who want to set up an internet radio station with which to encourage new ideas and disseminate local information, please contact WIDER EUROPE and find out how to get started.</p>

<p>Finally, WIDER EUROPE supports people globally, particularly in the Ukraine and other parts of the European Neighbourhood, as well as the Middle East and North Africa, who are seeking to overcome repression, eliminate fear, achieve freedom, establish democracies and apply good governance.</p>
</section>